version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: weather-redis
    ports:
      - "6379:6379"

  weather-service:
    build: .
    container_name: weather-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
